[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/FinJar-0.0.1-SNAPSHOT.jar"

[variables]
SPRING_PROFILES_ACTIVE = "prod"
